export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOADING: 'LOADING',
  UPDATE_ITEM: 'UPDATE_ITEM',
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  GET_ITEM: 'GET_ITEM',
  SEARCH_QUERY: 'SEARCH_QUERY',
}
